'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class CM_Header

    '''<summary>
    '''CMHeaderForm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CMHeaderForm As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''CMHeaderScriptManager control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CMHeaderScriptManager As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''CMHeaderUpdatePanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CMHeaderUpdatePanel As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''ClientScreenWidth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ClientScreenWidth As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''ClientScreenHeight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ClientScreenHeight As Global.System.Web.UI.WebControls.HiddenField
End Class
