'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class MedSurg_Pricelist

    '''<summary>
    '''MedSurgPricelistForm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MedSurgPricelistForm As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''hiddenFieldPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hiddenFieldPanel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''RefreshPricelistGridOnSubmit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RefreshPricelistGridOnSubmit As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''fvFSSPriceList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fvFSSPriceList As Global.System.Web.UI.WebControls.FormView

    '''<summary>
    '''FSSPriceListSummaryDataSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FSSPriceListSummaryDataSource As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''btnAddFSSPrice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddFSSPrice As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''pnlAddFSSPrice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlAddFSSPrice As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''tbAddCatalogNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbAddCatalogNumber As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''dlAddSin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dlAddSin As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''tbAddFSSPrice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbAddFSSPrice As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''dlAddPackage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dlAddPackage As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''FSSEffectiveDateTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FSSEffectiveDateTextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''FSSExpirationDateTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FSSExpirationDateTextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbAddLongDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbAddLongDescription As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnSaveFSSPrice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSaveFSSPrice As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnAddFSSPriceCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddFSSPriceCancel As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''gvFSSPriceList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvFSSPriceList As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''FSSPriceListDataSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FSSPriceListDataSource As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''fvBPAPriceList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fvBPAPriceList As Global.System.Web.UI.WebControls.FormView

    '''<summary>
    '''BPAPriceListSummaryDataSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BPAPriceListSummaryDataSource As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''btnBPAOpenAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnBPAOpenAdd As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''pnlBPAAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlBPAAdd As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''dlFSSCatalogNum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dlFSSCatalogNum As Global.VA.NAC.NACCMBrowser.BrowserObj.PaddedDropDownList

    '''<summary>
    '''BPA_FSS_Catalog_List control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BPA_FSS_Catalog_List As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''tbBPAFSSPrice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbBPAFSSPrice As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbBPAPrice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbBPAPrice As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''BPAEffectiveDateTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BPAEffectiveDateTextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''BPAExpirationDateTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BPAExpirationDateTextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbBPADescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbBPADescription As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnSaveBPA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSaveBPA As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnBPACancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnBPACancel As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''gvBPAPricelist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvBPAPricelist As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''BPAPriceListDataSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BPAPriceListDataSource As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''fvNonStandardBPAPriceList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fvNonStandardBPAPriceList As Global.System.Web.UI.WebControls.FormView

    '''<summary>
    '''NonStandardBPAPriceListSummaryDataSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NonStandardBPAPriceListSummaryDataSource As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''btnNonStandardBPAOpenAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnNonStandardBPAOpenAdd As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''pnlNonStandardBPAAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlNonStandardBPAAdd As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''tbNonStandardBPAPrice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbNonStandardBPAPrice As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''NonStandardBPAEffectiveDateTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NonStandardBPAEffectiveDateTextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''NonStandardBPAExpirationDateTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NonStandardBPAExpirationDateTextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbNonStandardBPADescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbNonStandardBPADescription As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnSaveNonStandardBPA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSaveNonStandardBPA As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnNonStandardBPACancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnNonStandardBPACancel As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''gvNonStandardBPAPricelist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvNonStandardBPAPricelist As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''NonStandardBPAPriceListDataSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NonStandardBPAPriceListDataSource As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''SINDataSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SINDataSource As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''PackageDataSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PackageDataSource As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''fvServicesPriceList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fvServicesPriceList As Global.System.Web.UI.WebControls.FormView

    '''<summary>
    '''ServicesPriceListSummaryDataSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ServicesPriceListSummaryDataSource As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''btnServicesOpenAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnServicesOpenAdd As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''pnlServicesAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlServicesAdd As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''servicesDropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents servicesDropDownList As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ServicesListDataSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ServicesListDataSource As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''tbServiceCategory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbServiceCategory As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbServiceFSSPrice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbServiceFSSPrice As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ServiceItemEffectiveDateTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ServiceItemEffectiveDateTextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ServiceItemExpirationDateTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ServiceItemExpirationDateTextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnSaveServices control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSaveServices As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnServicesCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnServicesCancel As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''gvServicesPricelist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvServicesPricelist As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''ServicesPriceListDataSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ServicesPriceListDataSource As Global.System.Web.UI.WebControls.SqlDataSource
End Class
