'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class NAC_CM_BPA_Edit

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''ScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''btnContractSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnContractSearch As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnMainMenu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnMainMenu As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnExit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnExit As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''fvContractInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fvContractInfo As Global.System.Web.UI.WebControls.FormView

    '''<summary>
    '''ContractDataSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ContractDataSource As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''ChecksDataSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ChecksDataSource As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''SalesDataSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SalesDataSource As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''SINDataSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SINDataSource As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''SBAAccompDataSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SBAAccompDataSource As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''SBACntrctrespDataSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SBACntrctrespDataSource As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''SBAPlanTypeDataSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SBAPlanTypeDataSource As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''dateExpirationdataSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dateExpirationdataSource As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''dateCompDataSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dateCompDataSource As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''businessSizeDataSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents businessSizeDataSource As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''vetStatusDataSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vetStatusDataSource As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''VendorTypeDateSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VendorTypeDateSource As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''GeoCoverageDataSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GeoCoverageDataSource As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''ReturnDataSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ReturnDataSource As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''SBAPlanDataSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SBAPlanDataSource As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CODataSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CODataSource As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StatedataSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatedataSource As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''AddSindataSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AddSindataSource As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''StateCoverageDataSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StateCoverageDataSource As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''QuarterDataSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents QuarterDataSource As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''SBAPlanProjections control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SBAPlanProjections As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''FSSContractDataSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FSSContractDataSource As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''IFFDataSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IFFDataSource As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''hfRefreshSales control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfRefreshSales As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''MsgBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MsgBox As Global.VA.NAC.NACCMBrowser.BrowserObj.MsgBox
End Class
