'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class NAC_Offers_Edit

    '''<summary>
    '''Form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''btnExit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnExit As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''StateDataSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StateDataSource As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''fvOfferRecord control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fvOfferRecord As Global.System.Web.UI.WebControls.FormView

    '''<summary>
    '''OfferDataSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OfferDataSource As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''ExpectDateDataSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ExpectDateDataSource As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''AuditDateDataSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AuditDateDataSource As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''ActionCompDataSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ActionCompDataSource As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CODataSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CODataSource As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''AssignmentDateDataSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AssignmentDateDataSource As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''ReassignDataSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ReassignDataSource As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''ProposalDataSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ProposalDataSource As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''ScheduleDataSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScheduleDataSource As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''ActionDataSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ActionDataSource As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''SolicitationDataSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SolicitationDataSource As Global.System.Web.UI.WebControls.SqlDataSource
End Class
