'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class pricelist_details

    '''<summary>
    '''PricelistDetailForm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PricelistDetailForm As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''fvPricelistDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fvPricelistDetail As Global.System.Web.UI.WebControls.FormView

    '''<summary>
    '''ServiceListDataSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ServiceListDataSource As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''UOMDataSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UOMDataSource As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''SINDataSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SINDataSource As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''ParentFSSItemsDataSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ParentFSSItemsDataSource As Global.System.Web.UI.WebControls.SqlDataSource
End Class
