//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace VA.NAC.CM.ApplicationStartup
{


    public partial class ContractPayments
    {

        /// <summary>
        /// PaymentUpdatePanelEventProxy control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VA.NAC.NACCMBrowser.BrowserObj.UpdatePanelEventProxy PaymentUpdatePanelEventProxy;

        /// <summary>
        /// PaymentUpdatePanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.UpdatePanel PaymentUpdatePanel;

        /// <summary>
        /// PaymentsHeaderFormView control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.FormView PaymentsHeaderFormView;

        /// <summary>
        /// PaymentGridPanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel PaymentGridPanel;

        /// <summary>
        /// PaymentScrollPos control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField PaymentScrollPos;

        /// <summary>
        /// highlightedPaymentRow control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField highlightedPaymentRow;

        /// <summary>
        /// highlightedPaymentRowOriginalColor control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField highlightedPaymentRowOriginalColor;

        /// <summary>
        /// confirmationMessageResults control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputHidden confirmationMessageResults;

        /// <summary>
        /// promptMessageResults control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputHidden promptMessageResults;

        /// <summary>
        /// PaymentGridViewDiv control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl PaymentGridViewDiv;

        /// <summary>
        /// PaymentGridView control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VA.NAC.NACCMBrowser.BrowserObj.GridView PaymentGridView;

        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new VA.NAC.CM.ApplicationStartup.ContractView Master
        {
            get
            {
                return ( ( VA.NAC.CM.ApplicationStartup.ContractView )( base.Master ) );
            }
        }
    }
}
