//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace VA.NAC.CM.ApplicationStartup {
    
    
    public partial class ItemPriceDetails {
        
        /// <summary>
        /// ItemPriceDetailsForm control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm ItemPriceDetailsForm;
        
        /// <summary>
        /// ItemPriceDetailsScriptManager control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.ScriptManager ItemPriceDetailsScriptManager;
        
        /// <summary>
        /// SelectedItemHeaderUpdatePanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.UpdatePanel SelectedItemHeaderUpdatePanel;
        
        /// <summary>
        /// SelectedItemHeader control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VA.NAC.CM.ApplicationStartup.ItemHeader SelectedItemHeader;
        
        /// <summary>
        /// PrintItemPriceDetailsButton control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button PrintItemPriceDetailsButton;
        
        /// <summary>
        /// UpdateItemPriceDetailsButton control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button UpdateItemPriceDetailsButton;
        
        /// <summary>
        /// CancelItemPriceDetailsButton control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button CancelItemPriceDetailsButton;
        
        /// <summary>
        /// ItemPriceDetailsBodyPanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel ItemPriceDetailsBodyPanel;
        
        /// <summary>
        /// ItemPriceDetailsUpdateUpdatePanelEventProxy control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VA.NAC.NACCMBrowser.BrowserObj.UpdatePanelEventProxy ItemPriceDetailsUpdateUpdatePanelEventProxy;
        
        /// <summary>
        /// ItemPriceDetailsFormView control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.FormView ItemPriceDetailsFormView;
        
        /// <summary>
        /// MsgBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VA.NAC.NACCMBrowser.BrowserObj.MsgBox MsgBox;
    }
}
