//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace VA.NAC.CM.ApplicationStartup {
    
    
    public partial class Items {
        
        /// <summary>
        /// medSurgItemForm control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm medSurgItemForm;
        
        /// <summary>
        /// ItemsScriptManager control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.ScriptManager ItemsScriptManager;
        
        /// <summary>
        /// ItemHeaderPanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel ItemHeaderPanel;
        
        /// <summary>
        /// ItemHeaderUpdatePanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.UpdatePanel ItemHeaderUpdatePanel;
        
        /// <summary>
        /// ItemGridProgressIndicator control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl ItemGridProgressIndicator;
        
        /// <summary>
        /// MainHeaderTitleLabel1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label MainHeaderTitleLabel1;
        
        /// <summary>
        /// formCloseButton control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button formCloseButton;
        
        /// <summary>
        /// MainHeaderTitleLabel2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label MainHeaderTitleLabel2;
        
        /// <summary>
        /// PrintItemsAndPricesButton control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button PrintItemsAndPricesButton;
        
        /// <summary>
        /// PrintScreenButton control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button PrintScreenButton;
        
        /// <summary>
        /// MainHeaderTitleLabel3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label MainHeaderTitleLabel3;
        
        /// <summary>
        /// MainHeaderItemCount control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label MainHeaderItemCount;
        
        /// <summary>
        /// AddNewItemButton control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button AddNewItemButton;
        
        /// <summary>
        /// ItemSearchLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label ItemSearchLabel;
        
        /// <summary>
        /// ItemSearchTextBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VA.NAC.NACCMBrowser.BrowserObj.TextBox ItemSearchTextBox;
        
        /// <summary>
        /// SearchButton control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button SearchButton;
        
        /// <summary>
        /// ClearSearchButton control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button ClearSearchButton;
        
        /// <summary>
        /// ItemFilterRadioButtonList control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RadioButtonList ItemFilterRadioButtonList;
        
        /// <summary>
        /// scrollPos control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputHidden scrollPos;
        
        /// <summary>
        /// avgRowHeight control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputHidden avgRowHeight;
        
        /// <summary>
        /// highlightedItemRow control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputHidden highlightedItemRow;
        
        /// <summary>
        /// highlightedItemRowOriginalColor control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputHidden highlightedItemRowOriginalColor;
        
        /// <summary>
        /// highlightedItemPriceRow control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputHidden highlightedItemPriceRow;
        
        /// <summary>
        /// highlightedItemPriceRowOriginalColor control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputHidden highlightedItemPriceRowOriginalColor;
        
        /// <summary>
        /// confirmationMessageResults control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputHidden confirmationMessageResults;
        
        /// <summary>
        /// promptMessageResults control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputHidden promptMessageResults;
        
        /// <summary>
        /// ContextMenuRowIndex_ItemsGridView control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputHidden ContextMenuRowIndex_ItemsGridView;
        
        /// <summary>
        /// ItemsGridViewDiv control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl ItemsGridViewDiv;
        
        /// <summary>
        /// InsertItemButtonClickUpdatePanelEventProxy control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VA.NAC.NACCMBrowser.BrowserObj.UpdatePanelEventProxy InsertItemButtonClickUpdatePanelEventProxy;
        
        /// <summary>
        /// ChangeItemHighlightUpdatePanelEventProxy control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VA.NAC.NACCMBrowser.BrowserObj.UpdatePanelEventProxy ChangeItemHighlightUpdatePanelEventProxy;
        
        /// <summary>
        /// SelectParentItemForBPAUpdatePanelEventProxy control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VA.NAC.NACCMBrowser.BrowserObj.UpdatePanelEventProxy SelectParentItemForBPAUpdatePanelEventProxy;
        
        /// <summary>
        /// SelectServiceCategoryUpdatePanelEventProxy control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VA.NAC.NACCMBrowser.BrowserObj.UpdatePanelEventProxy SelectServiceCategoryUpdatePanelEventProxy;
        
        /// <summary>
        /// RightClickUpdatePanelEventProxy control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VA.NAC.NACCMBrowser.BrowserObj.UpdatePanelEventProxy RightClickUpdatePanelEventProxy;
        
        /// <summary>
        /// PageGridViewUpdatePanelEventProxy control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VA.NAC.NACCMBrowser.BrowserObj.UpdatePanelEventProxy PageGridViewUpdatePanelEventProxy;
        
        /// <summary>
        /// ItemsGridViewUpdatePanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.UpdatePanel ItemsGridViewUpdatePanel;
        
        /// <summary>
        /// ItemContextMenu control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VA.NAC.NACCMBrowser.BrowserObj.ContextMenu ItemContextMenu;
        
        /// <summary>
        /// ItemsGridView control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VA.NAC.NACCMBrowser.BrowserObj.GridView ItemsGridView;
        
        /// <summary>
        /// PagerUpdatePanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.UpdatePanel PagerUpdatePanel;
        
        /// <summary>
        /// ItemPager control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VA.NAC.NACCMBrowser.BrowserObj.Pager ItemPager;
        
        /// <summary>
        /// SelectedItemHeaderUpdatePanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.UpdatePanel SelectedItemHeaderUpdatePanel;
        
        /// <summary>
        /// SelectedItemHeader control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VA.NAC.CM.ApplicationStartup.ItemHeader SelectedItemHeader;
        
        /// <summary>
        /// PriceFilterChangeUpdatePanelEventProxy control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VA.NAC.NACCMBrowser.BrowserObj.UpdatePanelEventProxy PriceFilterChangeUpdatePanelEventProxy;
        
        /// <summary>
        /// PriceHeader2UpdatePanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.UpdatePanel PriceHeader2UpdatePanel;
        
        /// <summary>
        /// AddNewPriceButton control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button AddNewPriceButton;
        
        /// <summary>
        /// PriceFilterCheckBoxList control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBoxList PriceFilterCheckBoxList;
        
        /// <summary>
        /// priceScrollPos control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputHidden priceScrollPos;
        
        /// <summary>
        /// ItemPricesGridViewDiv control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl ItemPricesGridViewDiv;
        
        /// <summary>
        /// RefreshPricesButtonClickUpdatePanelEventProxy control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VA.NAC.NACCMBrowser.BrowserObj.UpdatePanelEventProxy RefreshPricesButtonClickUpdatePanelEventProxy;
        
        /// <summary>
        /// InsertPriceButtonClickUpdatePanelEventProxy control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VA.NAC.NACCMBrowser.BrowserObj.UpdatePanelEventProxy InsertPriceButtonClickUpdatePanelEventProxy;
        
        /// <summary>
        /// EditCancelPriceButtonClickUpdatePanelEventProxy control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VA.NAC.NACCMBrowser.BrowserObj.UpdatePanelEventProxy EditCancelPriceButtonClickUpdatePanelEventProxy;
        
        /// <summary>
        /// ChangeItemPriceHighlightUpdatePanelEventProxy control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VA.NAC.NACCMBrowser.BrowserObj.UpdatePanelEventProxy ChangeItemPriceHighlightUpdatePanelEventProxy;
        
        /// <summary>
        /// PriceListChangeUpdatePanelEventProxy control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VA.NAC.NACCMBrowser.BrowserObj.UpdatePanelEventProxy PriceListChangeUpdatePanelEventProxy;
        
        /// <summary>
        /// ItemPricesGridViewUpdatePanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.UpdatePanel ItemPricesGridViewUpdatePanel;
        
        /// <summary>
        /// ItemPricesGridView control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VA.NAC.NACCMBrowser.BrowserObj.GridView ItemPricesGridView;
        
        /// <summary>
        /// RefreshItemScreenOnSubmit control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField RefreshItemScreenOnSubmit;
        
        /// <summary>
        /// RefreshItemPriceScreenOnSubmit control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField RefreshItemPriceScreenOnSubmit;
        
        /// <summary>
        /// RebindItemScreenOnRefreshOnSubmit control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField RebindItemScreenOnRefreshOnSubmit;
        
        /// <summary>
        /// RebindItemPriceScreenOnRefreshOnSubmit control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField RebindItemPriceScreenOnRefreshOnSubmit;
        
        /// <summary>
        /// RefreshItemHeaderCountOnSubmit control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField RefreshItemHeaderCountOnSubmit;
        
        /// <summary>
        /// ServerConfirmationDialogResults control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField ServerConfirmationDialogResults;
        
        /// <summary>
        /// MsgBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VA.NAC.NACCMBrowser.BrowserObj.MsgBox MsgBox;
    }
}
