//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace VA.NAC.CM.ApplicationStartup {
    
    
    public partial class UserRecentDocumentsBody {
        
        /// <summary>
        /// UserRecentDocumentsUpdatePanelEventProxy control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VA.NAC.NACCMBrowser.BrowserObj.UpdatePanelEventProxy UserRecentDocumentsUpdatePanelEventProxy;
        
        /// <summary>
        /// UserRecentDocumentsUpdatePanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.UpdatePanel UserRecentDocumentsUpdatePanel;
        
        /// <summary>
        /// UserRecentDocumentsGridPanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel UserRecentDocumentsGridPanel;
        
        /// <summary>
        /// SearchScrollPos control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField SearchScrollPos;
        
        /// <summary>
        /// highlightedSearchRow control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField highlightedSearchRow;
        
        /// <summary>
        /// highlightedSearchRowOriginalColor control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField highlightedSearchRowOriginalColor;
        
        /// <summary>
        /// confirmationMessageResults control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputHidden confirmationMessageResults;
        
        /// <summary>
        /// promptMessageResults control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputHidden promptMessageResults;
        
        /// <summary>
        /// UserRecentDocumentsGridViewDiv control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl UserRecentDocumentsGridViewDiv;
        
        /// <summary>
        /// ChangeItemHighlightUpdatePanelEventProxy control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VA.NAC.NACCMBrowser.BrowserObj.UpdatePanelEventProxy ChangeItemHighlightUpdatePanelEventProxy;
        
        /// <summary>
        /// UserRecentDocumentsGridViewUpdatePanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.UpdatePanel UserRecentDocumentsGridViewUpdatePanel;
        
        /// <summary>
        /// UserRecentDocumentsGridView control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VA.NAC.NACCMBrowser.BrowserObj.GridView UserRecentDocumentsGridView;
        
        /// <summary>
        /// RefreshContractSelectScreenOnSubmit control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField RefreshContractSelectScreenOnSubmit;
        
        /// <summary>
        /// RebindContractSelectScreenOnRefreshOnSubmit control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField RebindContractSelectScreenOnRefreshOnSubmit;
        
        /// <summary>
        /// ReselectPreviouslySelectedItem control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField ReselectPreviouslySelectedItem;
        
        /// <summary>
        /// MsgBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VA.NAC.NACCMBrowser.BrowserObj.MsgBox MsgBox;
        
        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new VA.NAC.CM.ApplicationStartup.UserRecentDocuments Master {
            get {
                return ((VA.NAC.CM.ApplicationStartup.UserRecentDocuments)(base.Master));
            }
        }
    }
}
